tests/tokenizeur/scripts/affectation.43.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison variable $cause 280 "!==" _constant null" )
          block 
          0 : 
              affectation 
              left : 
                  property variable $xliterals a->
               "=" 
              right : 
                  variable $b
          1 : 
              affectation 
              left : 
                  property variable $xliterals b->
              273 ".=" 
              right : 
                  concatenation 
                  0 : 
                      literals  c: 
                  1 : 
                      method variable $d
                      method call : functioncall 307 "e" ( ( ) ) : 
                          functioncall e
                          function call : 307 "e": 
                              arglist 
                              Empty arglist
                  2 : 
                      literals f
