tests/tokenizeur/scripts/affectation.54.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          cast (292 "(array)")variable $x
              variable $x
       "=" 
      right : 
          method variable $a
          method call : functioncall 307 "b" ( arglist(variable $c) ) : 
              functioncall b
              function call : 307 "b": 
                  arglist 
                  0 : 
                      variable $c
