tests/tokenizeur/scripts/arrayfct.6.test.php
  codephp <?php

  code : 
      functioncall array
      function call : 360 "array": 
          arglist 
          0 : 
              literals 1 => literals 2
                  literals 1
                  literals 2
          1 : 
              literals 3 => literals 4
                  literals 3
                  literals 4
          2 : 
              variable $x => variable $y
                  variable $x
                  variable $y
          3 : 
              literals 5 => functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3) ) 
                  literals 5
                  functioncall array
                  function call : 360 "array": 
                      arglist 
                      0 : 
                          literals 1
                      1 : 
                          literals 2
                      2 : 
                          literals 3
