tests/tokenizeur/scripts/block.5.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "logical comparison variable $a 283 "==" _array variable $b[literals c] 278 "||" parenthesis (comparison variable $d 283 "==" literals )" )
              block 
              0 : 
                  functioncall echo
                  function call : 316 "echo": 
                      arglist 
                      0 : 
                          literals e
      1 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals f
