tests/tokenizeur/scripts/block.3.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "functioncall 351 "empty" ( arglist(_array variable $row[literals 0]) ) " )
          block 
          0 : 
              affectation 
              left : 
                  _array
                      variable $date_choisie
                      literals 0
               "=" 
              right : 
                  functioncall date
                  function call : 307 "date": 
                      arglist 
                      0 : 
                          literals Y
          1 : 
              literals 1
          2 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
