tests/tokenizeur/scripts/class.18.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"347 "static"variable $a = literals 1
          1 : 
               343 "protected"347 "static"variable $b = literals 1
          2 : 
               342 "public"347 "static"variable $c = literals 1
          3 : 
               342 "public"347 "static"variable $d = literals 1
          4 : 
               344 "private"347 "static"variable $e = literals 1
          5 : 
               344 "private"347 "static"variable $f = literals 1
