tests/tokenizeur/scripts/class.21.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"variable $input
          1 : 
               343 "protected"variable $output = literals 
          2 : 
              function literals x ( )
                  block 
                  0 : 
                      _return 
                      return : "_constant true"
