tests/tokenizeur/scripts/codephp.5.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "  Espace vide  ""
      2 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
