tests/tokenizeur/scripts/codephp.21.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  variable $a
      1 : 
          rawtext 
          Texte : "311 "b""
      2 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  variable $c
      3 : 
          rawtext 
          Texte : "311 "d""
      4 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals e 
