tests/tokenizeur/scripts/codephp.25.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $b" )
          block 
          0 : 
              rawtext 
              Texte : "311 """
          1 : 
              variable $a297 "++" 
                  variable $a
          2 : 
              rawtext 
              Texte : "311 """
  rawtext 
  Texte : "311 "C""
