tests/tokenizeur/scripts/codephp.13.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "raw
""
      2 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  variable $x
      3 : 
          variable $y
