tests/tokenizeur/scripts/comparison.16.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison logical comparison variable $x 283 "==" literals 2 263 "OR" _constant PHPVERSION 282 "!=" literals s" )
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
