tests/tokenizeur/scripts/comparison.18.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison variable $a 283 "==" constant_static 380 "\"\307 "b"::_constant c" )
          block 
          0 : 
              _return 
              return : "variable $d"
       else 
          block 
          0 : 
              _return 
              return : "literals f"
