tests/tokenizeur/scripts/concatenation.11.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $z
       "=" 
      right : 
          concatenation 
          0 : 
              noscream @
                  functioncall y
                  function call : 307 "y": 
                      arglist 
                      0 : 
                          literals 1
          1 : 
              literals a
          2 : 
              variable $c
