tests/tokenizeur/scripts/concatenation.29.test.php
  rawtext 
  Texte : "311 "A""
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  functioncall a
                  function call : 307 "a": 
                      arglist 
                      0 : 
                          variable $b
      1 : 
          rawtext 
          Texte : "311 """"
      2 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "functioncall 307 "defined" ( arglist(literals c) ) " )
              block 
              0 : 
                  functioncall echo
                  function call : 316 "echo": 
                      arglist 
                      0 : 
                          literals d
  rawtext 
  Texte : "311 "E""
