tests/tokenizeur/scripts/constant_class.4.test.php
  codephp <?php

  code : 
       class 307 "MyMin"
          block 
          0 : 
              constant_class               _constant a = literals 1 
          1 : 
              constant_class               _constant b = literals 2 
          2 : 
              constant_class               _constant c = literals 3 
          3 : 
              constant_class               _constant d = literals 4.2 
