tests/tokenizeur/scripts/constant_class.5.test.php
  codephp <?php

  code : 
       class 307 "MyMin"
          block 
          0 : 
              constant_class               _constant a = literals 1 
          1 : 
              constant_class               _constant b = literals 2 
          2 : 
              constant_class               _constant c = literals 3 
          3 : 
              constant_class               _constant ac = literals 1 
          4 : 
              constant_class               _constant bc = literals 2 
          5 : 
              constant_class               _constant cc = literals 3 
          6 : 
              constant_class               _constant ad = literals 1 
