tests/tokenizeur/scripts/dowhile.3.test.php
  codephp <?php

  code : 
      function literals h ( )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parenthesis 
                  ( "comparison _constant false 281 "===" method_static 307 "f"::functioncall 307 "g" ( ( ) ) " )
                  block 
                  0 : 
                      _dowhile 
                          block 
                          0 : 
                              affectation 
                              left : 
                                  variable $command
                               "=" 
                              right : 
                                  method_static 
                                  307 "a"::functioncall 307 "b" ( ( ) ) : 
                                      functioncall b
                                      function call : 307 "b": 
                                          arglist 
                                          Empty arglist
                          parenthesis 
                          ( "postplusplus 297 "++"variable $i" )
               else 
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $c
                       "=" 
                      right : 
                          method variable $d
                          method call : functioncall 307 "e" ( ( ) ) : 
                              functioncall e
                              function call : 307 "e": 
                                  arglist 
                                  Empty arglist
