tests/tokenizeur/scripts/for.2.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        End  : comparison variable $i  "<" functioncall 307 "count" ( arglist(variable $tab_rac) ) ;
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              literals 1
          1 : 
              affectation 
              left : 
                  _array
                      _array
                          variable $x
                          literals 1
                      literals 2
               "=" 
              right : 
                  literals 2
