tests/tokenizeur/scripts/for.13.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $i  "=" literals 0
affectation variable $a  "=" literals 1 };
        End  : comparison variable $i  "<" literals 0;
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              left : 
                  variable $w
               "=" 
              right : 
                  literals 1
