tests/tokenizeur/scripts/for.17.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $i  "=" literals 0
affectation variable $a  "=" literals 1 };
        End  : block {comparison variable $i  "<" literals 0
affectation variable $b  "=" literals 2 };
        Incr : block {postplusplus 297 "++"variable $i
affectation variable $c  "=" literals 3 };
          block 
          0 : 
              affectation 
              left : 
                  variable $w
               "=" 
              right : 
                  literals 1
