tests/tokenizeur/scripts/for.34.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        End  : block {comparison variable $a  "<" literals 1
postplusplus 297 "++"variable $c };
        Incr : affectation variable $b 277 "+=" literals 2;
          block 
          0 : 
              affectation 
              left : 
                  variable $d
               "=" 
              right : 
                  literals 1
