tests/tokenizeur/scripts/foreach.21.test.php
  codephp <?php

  code : 
      _foreach (variable $x as variable $y => variable $z)
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
          1 : 
              affectation 
              left : 
                  variable $y
               "=" 
              right : 
                  literals 2
