tests/tokenizeur/scripts/functioncall.7.test.php
  codephp <?php

  code : 
      functioncall x
      function call : 307 "x": 
          arglist 
          0 : 
              literals 1
          1 : 
              literals 2
          2 : 
              literals 3
          3 : 
              variable $x
          4 : 
              functioncall x
              function call : 307 "x": 
                  arglist 
                  Empty arglist
