tests/tokenizeur/scripts/functioncall.53.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals 1
              1 : 
                  ternaryop ?
                  literals 2 ? literals 2 : literals 3
                      literals 2
                      literals 2
                      literals 3
              2 : 
                  literals 5
      1 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals 1
              1 : 
                  property variable $xliterals y->
              2 : 
                  ternaryop ?
                  literals 1 ? literals 2 : literals 3
                      literals 1
                      literals 2
                      literals 3
              3 : 
                  literals 5
