tests/tokenizeur/scripts/functioncall.52.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall \
          function call : 307 "a"\307 "b"\307 "c"\307 "strtolower": 
              arglist 
              0 : 
                  literals a
      1 : 
          functioncall print
          function call : 266 "print": 
              arglist 
              0 : 
                  functioncall \
                  function call : 380 "\"\307 "strtolower": 
                      arglist 
                      0 : 
                          literals a
