tests/tokenizeur/scripts/functioncall.17.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals 1
              1 : 
                  literals 1
      1 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  literals 1
