tests/tokenizeur/scripts/function.13.test.php
  codephp <?php

  code : 
      function literals a arglist(affectation reference &variable $b  "=" functioncall 360 "array" ( arglist(literals 1, keyvalue literals 2 => functioncall 360 "array" ( arglist(literals 3, literals 2) ) , literals 3) ) , affectation reference &variable $c  "=" literals 1, reference &variable $d)
          block 
          0 : 
              functioncall print_r
              function call : 307 "print_r": 
                  arglist 
                  0 : 
                      variable $b
