tests/tokenizeur/scripts/ifthen.28.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
          1 : 
              rawtext 
              Texte : "311 "texte brut1
""
      Condition 1) 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              left : 
                  variable $y
               "=" 
              right : 
                  literals 2
          1 : 
              rawtext 
              Texte : "311 "texte brut2

""
