tests/tokenizeur/scripts/ifthen.64.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $s" )
          block 
          0 : 
              variable $x297 "++" 
                  variable $x
       else 
          block 
          0 : 
              method property variable $x->literals y
              method call : functioncall 307 "f" ( ( ) ) : 
                  functioncall f
                  function call : 307 "f": 
                      arglist 
                      Empty arglist
