tests/tokenizeur/scripts/ifthen.36.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  left : 
                      variable $x
                   "=" 
                  right : 
                      literals 1
           else 
              block 
              0 : 
                  _foreach (property variable $a->literals b as  => variable $c)
                      block 
                      0 : 
                          ifthen if
                          Condition 0) 
                              parenthesis 
                              ( "comparison variable $d 281 "===" _constant null" )
                              block 
                              0 : 
                                  affectation 
                                  left : 
                                      variable $e[]
                                          variable $e
                                   "=" 
                                  right : 
                                      reference &
                                           new 307 "f" arglist(literals ) 
                           else 
                              block 
                              0 : 
                                  affectation 
                                  left : 
                                      variable $g[]
                                          variable $g
                                   "=" 
                                  right : 
                                      reference &
                                          functioncall h
                                          function call : 307 "h": 
                                              arglist 
                                              0 : 
                                                  variable $e
      1 : 
          affectation 
          left : 
              variable $dd[]
                  variable $dd
           "=" 
          right : 
              literals 1
