tests/tokenizeur/scripts/ifthen.9.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "literals a" )
          block 
          0 : 
              literals 1
      Condition 1) 
          parenthesis 
          ( "literals b" )
          block 
          0 : 
              literals 2
       else 
          block 
          0 : 
              literals 3
