tests/tokenizeur/scripts/ifthen.38.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison variable $a 283 "==" literals b" )
          block 
          0 : 
              affectation 
              left : 
                  property variable $cliterals d->
               "=" 
              right : 
                  method variable $e
                  method call : functioncall 307 "f" ( ( ) ) : 
                      functioncall f
                      function call : 307 "f": 
                          arglist 
                          Empty arglist
