tests/tokenizeur/scripts/ifthen.49.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "functioncall 307 "preg_match" ( arglist(variable $pattern, variable $path, variable $matches) ) " )
          block 
          0 : 
              _return 
              return : "_array variable $matches[literals 1]"
       else 
          block 
          0 : 
              invert ~
                  sign  "-"literals 1
                      literals 1
