tests/tokenizeur/scripts/ifthen.8.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $condition" )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parenthesis 
                  ( "variable $condition2" )
                  block 
                  0 : 
                      literals a
       else 
          block 
          0 : 
              literals b
