tests/tokenizeur/scripts/ifthen.43.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "variable $a" )
              block 
              0 : 
                  affectation 
                  left : 
                      _array
                          _array
                              property variable $bliterals c->
                              literals 0
                          literals d
                  273 ".=" 
                  right : 
                      literals e
      1 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "variable $a" )
              block 
              0 : 
                  affectation 
                  left : 
                      _array
                          property property variable $b->literals cliterals d->
                          literals e
                  273 ".=" 
                  right : 
                      literals f
