tests/tokenizeur/scripts/ifthen.6.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $condition" )
          block 
          0 : 
              literals a
       else 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "variable $condition" )
              block 
              0 : 
                  literals b
           else 
              block 
              0 : 
                  literals c
