tests/tokenizeur/scripts/ifthen.59.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison variable $a 283 "==" literals 1" )
          block 
          0 : 
              affectation 
              left : 
                  variable $b
              277 "+=" 
              right : 
                  literals 1
       else 
          block 
          0 : 
              affectation 
              left : 
                  variable $c
              273 ".=" 
              right : 
                  literals d
