tests/tokenizeur/scripts/ifthen.55.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $x" )
          block 
          0 : 
              concatenation 
              0 : 
                  literals c
              1 : 
                  literals d
       else 
          block 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  literals b
