tests/tokenizeur/scripts/ifthen.51.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "comparison variable $a 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              left : 
                  variable $b
               "=" 
              right : 
                  literals 1
       else 
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parenthesis 
                  ( "comparison variable $c 283 "==" literals 2" )
                  block 
                  0 : 
                      functioncall echo
                      function call : 316 "echo": 
                          arglist 
                          0 : 
                              literals 3
                  1 : 
                      ifthen if
                      Condition 0) 
                          parenthesis 
                          ( "comparison variable $d 283 "==" literals " )
                          block 
                          0 : 
                              affectation 
                              left : 
                                  variable $e
                               "=" 
                              right : 
                                  literals 4
                       else 
                          block 
                          0 : 
                              affectation 
                              left : 
                                  variable $f
                               "=" 
                              right : 
                                  literals 5
                  2 : 
                      affectation 
                      left : 
                          variable $g
                       "=" 
                      right : 
                          literals 6
              Condition 1) 
                  parenthesis 
                  ( "affectation variable $h  "=" literals 7" )
                  block 
