tests/tokenizeur/scripts/ifthen.11.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $condition" )
          block 
          0 : 
              literals a
      Condition 1) 
          parenthesis 
          ( "variable $condition2" )
          block 
          0 : 
              literals b
      Condition 2) 
          parenthesis 
          ( "variable $condition3" )
          block 
          0 : 
              literals c
