tests/tokenizeur/scripts/ifthen.27.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
          1 : 
              rawtext 
              Texte : "311 "texte brut1
""
