tests/tokenizeur/scripts/ifthen.60.test.php
  codephp <?php

  code : 
      _while 
          parenthesis 
          ( "variable $x" )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parenthesis 
                  ( "variable $x" )
                  block 
                  0 : 
                      variable $x297 "++" 
                          variable $x
               else 
                  block 
                  0 : 
                      _for 
                        Init : variable $i;
                        End  : comparison variable $i  "<" literals 1;
                        Incr : postplusplus 297 "++"variable $i;
                          block 
                          0 : 
                              variable $y297 "++" 
                                  variable $y
