tests/tokenizeur/scripts/ifthen.42.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $a" )
          block 
          0 : 
              affectation 
              left : 
                  property_static 307 "C"::variable $b->
               "=" 
              right : 
                  variable $d
       else 
          block 
          0 : 
              affectation 
              left : 
                  variable $e
               "=" 
              right : 
                  functioncall f
                  function call : 307 "f": 
                      arglist 
                      Empty arglist
