tests/tokenizeur/scripts/ifthen.54.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "variable $x" )
          block 
          0 : 
              variable $z297 "++" 
                  variable $z
       else 
          block 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  literals b
