tests/tokenizeur/scripts/inclusion.15.test.php
  codephp <?php

  code : 
      inclusion include
          affectation 
          left : 
              variable $a
           "=" 
          right : 
              method variable $b
              method call : functioncall 307 "c" ( arglist(variable $d) ) : 
                  functioncall c
                  function call : 307 "c": 
                      arglist 
                      0 : 
                          variable $d
