tests/tokenizeur/scripts/keyvalue.5.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $TABINDEX
       "=" 
      right : 
          functioncall array
          function call : 360 "array": 
              arglist 
              0 : 
                  operation 
                  left : 
                      literals bouton0 => literals 1
                          literals bouton0
                          literals 1
                  operation :  "+"
                  right : 
                      literals 2
