tests/tokenizeur/scripts/keyvalue.2.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $TABINDEX
       "=" 
      right : 
          functioncall array
          function call : 360 "array": 
              arglist 
              0 : 
                  literals bouton0 => postplusplus 297 "++"variable $nbtab
                      literals bouton0
                      variable $nbtab297 "++" 
                          variable $nbtab
              1 : 
                  literals bouton1 => postplusplus 297 "++"variable $nbtab
                      literals bouton1
                      variable $nbtab297 "++" 
                          variable $nbtab
              2 : 
                  literals bouton2 => postplusplus 297 "++"variable $nbtab
                      literals bouton2
                      variable $nbtab297 "++" 
                          variable $nbtab
