tests/tokenizeur/scripts/keyvalue.3.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $TABINDEX
       "=" 
      right : 
          functioncall array
          function call : 360 "array": 
              arglist 
              0 : 
                  literals bouton0 => preplusplus variable $nbtab297 "++"
                      literals bouton0
                      297 "++"variable $nbtab 
                          variable $nbtab
              1 : 
                  literals bouton1 => preplusplus variable $nbtab297 "++"
                      literals bouton1
                      297 "++"variable $nbtab 
                          variable $nbtab
              2 : 
                  literals bouton2 => preplusplus variable $nbtab297 "++"
                      literals bouton2
                      297 "++"variable $nbtab 
                          variable $nbtab
