tests/tokenizeur/scripts/logical.44.test.php
  rawtext 
  Texte : "311 "A""
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  method variable $c
                  method call : functioncall 307 "a" ( arglist(variable $b) ) : 
                      functioncall a
                      function call : 307 "a": 
                          arglist 
                          0 : 
                              variable $b
      1 : 
          rawtext 
          Texte : "311 "|""
      2 : 
          functioncall echo
          function call : 316 "echo": 
              arglist 
              0 : 
                  variable $d
  rawtext 
  Texte : "311 "B""
