tests/tokenizeur/scripts/logical.42.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "logical logical logical logical logical _constant A  "&" variable $b 278 "||" _constant C  "&" variable $d 278 "||" _constant E  "&" variable $f" )
          block 
          0 : 
              affectation 
              left : 
                  variable $g
               "=" 
              right : 
                  literals 1
