tests/tokenizeur/scripts/logical.14.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parenthesis 
          ( "logical literals 1 279 "&&" comparison _array property variable $a->literals b[variable $c] 281 "===" literals @" )
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
