tests/tokenizeur/scripts/logical.19.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          logical 
          left : 
              variable $x
          operateur : 278 "||"
          right : 
              variable $y
      1 : 
          logical 
          left : 
              variable $a
          operateur : 278 "||"
          right : 
              variable $b
      2 : 
          logical 
          left : 
              variable $c
          operateur : 278 "||"
          right : 
              variable $d
