tests/tokenizeur/scripts/logical.5.test.php
  codephp <?php

  code : 
      logical 
      left : 
          logical 
          left : 
              logical 
              left : 
                  logical 
                  left : 
                      literals 1
                  operateur : 265 "and"
                  right : 
                      literals 2
              operateur : 263 "or"
              right : 
                  literals 3
          operateur : 264 "xor"
          right : 
              literals 4
      operateur : 265 "and"
      right : 
          literals 5
