tests/tokenizeur/scripts/method.19.test.php
  codephp <?php

  code : 
      method variable $a
      method call : functioncall 307 "b" ( arglist(method variable $c->functioncall 307 "d" ( ( ) ) , literals 340) ) : 
          functioncall b
          function call : 307 "b": 
              arglist 
              0 : 
                  method variable $c
                  method call : functioncall 307 "d" ( ( ) ) : 
                      functioncall d
                      function call : 307 "d": 
                          arglist 
                          Empty arglist
              1 : 
                  literals 340
