tests/tokenizeur/scripts/method_static.5.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $result
       "=" 
      right : 
          method_static 
          307 "Classe"::functioncall variable $a ( arglist(variable $b, variable $c, variable $d) ) : 
              functioncall $a
              function call : variable $a: 
                  arglist 
                  0 : 
                      variable $b
                  1 : 
                      variable $c
                  2 : 
                      variable $d
