tests/tokenizeur/scripts/opappend.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              functioncall array
              function call : 360 "array": 
                  arglist 
                  0 : 
                      literals 1
                  1 : 
                      literals 2
      1 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              reference &
                  variable $x[]
                      variable $x
