tests/tokenizeur/scripts/operation.10.test.php
  codephp <?php

  code : 
      operation 
      left : 
          operation 
          left : 
              literals 1
          operation :  "*"
          right : 
              literals 2
      operation :  "+"
      right : 
          operation 
          left : 
              literals 3
          operation :  "*"
          right : 
              literals 4
