tests/tokenizeur/scripts/operation.47.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $x
       "=" 
      right : 
          operation 
          left : 
              operation 
              left : 
                  parenthesis 
                  ( "operation property variable $c->literals y  "-" property property variable $a->literals b->literals c" )
              operation :  "*"
              right : 
                  operation 
                  left : 
                      property variable $dliterals e->
                  operation :  "+"
                  right : 
                      property property variable $f->literals gliterals h->
          operation :  "+"
          right : 
              operation 
              left : 
                  property variable $iliterals j->
              operation :  "*"
              right : 
                  parenthesis 
                  ( "operation literals 1  "-" variable $k" )
