tests/tokenizeur/scripts/operation.33.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $base
       "=" 
      right : 
          operation 
          left : 
              operation 
              left : 
                  variable $pad
              operation :  "+"
              right : 
                  variable $width
          operation :  "+"
          right : 
              variable $i297 "++" 
                  variable $i
