tests/tokenizeur/scripts/property_static.6.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              property_static 307 "self"::_array variable $a[literals b][]
                  property_static 307 "self"::_array variable $a[literals b]->
           "=" 
          right : 
              variable $d
      1 : 
          affectation 
          left : 
              property_static 307 "self"::_array _array variable $a[variable $b][literals 1][]
                  property_static 307 "self"::_array _array variable $a[variable $b][literals 1]->
           "=" 
          right : 
              variable $d
      2 : 
          affectation 
          left : 
              property_static 307 "self"::_array _array _array variable $a[variable $b][literals 1][_constant true][]
                  property_static 307 "self"::_array _array _array variable $a[variable $b][literals 1][_constant true]->
           "=" 
          right : 
              variable $d
