tests/tokenizeur/scripts/sequence.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $a
           "=" 
          right : 
              literals 1
      1 : 
          affectation 
          left : 
              variable $b
           "=" 
          right : 
              operation 
              left : 
                  literals 1
              operation :  "+"
              right : 
                  literals 1
      2 : 
          affectation 
          left : 
              variable $c
           "=" 
          right : 
              literals 3
