tests/tokenizeur/scripts/sequence.44.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          method_static 
          307 "a"::functioncall 307 "b" ( ( ) ) : 
              functioncall b
              function call : 307 "b": 
                  arglist 
                  Empty arglist
      1 : 
          method_static 
          380 "\"\307 "c"::functioncall 307 "d" ( arglist(literals e, _constant f) ) : 
              functioncall d
              function call : 307 "d": 
                  arglist 
                  0 : 
                      literals e
                  1 : 
                      _constant (                      f )
