tests/tokenizeur/scripts/sequence.16.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "literals 1" )
              block 
              0 : 
                  inclusion include_once
                      concatenation 
                      0 : 
                          literals ./a
                      1 : 
                          literals /b.inc
           else 
              block 
              0 : 
                  affectation 
                  left : 
                      variable $a
                   "=" 
                  right : 
                      literals 2
      1 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
