tests/tokenizeur/scripts/sequence.3.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $a
           "=" 
          right : 
              literals 1
      1 : 
          affectation 
          left : 
              variable $b
           "=" 
          right : 
              literals 2
      2 : 
          affectation 
          left : 
              variable $c
           "=" 
          right : 
              literals 3
