tests/tokenizeur/scripts/sequence.9.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parenthesis 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  left : 
                      variable $a
                   "=" 
                  right : 
                      literals 2
      1 : 
          rawtext 
          Texte : "311 " 3 ""
      2 : 
          affectation 
          left : 
              variable $b
           "=" 
          right : 
              literals 3
