tests/tokenizeur/scripts/sequence.8.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "2
""
      2 : 
          affectation 
          left : 
              variable $y
           "=" 
          right : 
              literals 3
