tests/tokenizeur/scripts/sign.12.test.php
  codephp <?php

  code : 
      functioncall print
      function call : 266 "print": 
          arglist 
          0 : 
              operation 
              left : 
                  variable $a
              operation :  "-"
              right : 
                  sign  "+"sign  "+"sign  "-"sign  "+"sign  "+"variable $b
                      sign  "+"sign  "-"sign  "+"sign  "+"variable $b
                          sign  "-"sign  "+"sign  "+"variable $b
                              sign  "+"sign  "+"variable $b
                                  sign  "+"variable $b
                                      variable $b
