tests/tokenizeur/scripts/sign.10.test.php
  codephp <?php

  code : 
      functioncall print
      function call : 266 "print": 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  parenthesis 
                  ( "operation operation parenthesis (operation parenthesis (operation variable $b  "-" variable $c)  "*" literals 2)  "+" parenthesis (operation literals 3  "-" variable $d)  "+" variable $e" )
              2 : 
                  literals f
