tests/tokenizeur/scripts/sign.21.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $u
       "=" 
      right : 
          sign  "-"cast (int)
              cast (295 "(int)")method variable $a->functioncall 307 "b" ( ( ) ) 
                  method variable $a
                  method call : functioncall 307 "b" ( ( ) ) : 
                      functioncall b
                      function call : 307 "b": 
                          arglist 
                          Empty arglist
