tests/tokenizeur/scripts/sign.11.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $CurrNav
       "=" 
      right : 
          functioncall array
          function call : 360 "array": 
              arglist 
              0 : 
                  sign  "-"literals 3
                      literals 3
              1 : 
                  literals last => sign  "-"literals 1
                      literals last
                      sign  "-"literals 1
                          literals 1
              2 : 
                  sign  "-"literals 2
                      literals 2
