tests/tokenizeur/scripts/switch.19.test.php
  codephp <?php

  code : 
      _switch 
          parenthesis 
          ( "variable $a" )
          block 
          0 : 
              _case 
                  literals a
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $z
                       "=" 
                      right : 
                          literals 1
                  1 : 
                      _break 
                      Number : " "1""
          1 : 
              _default 
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $z
                       "=" 
                      right : 
                          literals 3
                  1 : 
                      _break 
                      Number : " "1""
