tests/tokenizeur/scripts/switch.18.test.php
  codephp <?php

  code : 
      _switch 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              _case 
                  literals 2
                  block 
          1 : 
              _case 
                  literals 3
                  block 
          2 : 
              _default 
                  block 
                  0 : 
                      functioncall echo
                      function call : 316 "echo": 
                          arglist 
                          0 : 
                              literals 4
                  1 : 
                      functioncall echo
                      function call : 316 "echo": 
                          arglist 
                          0 : 
                              literals 5
