tests/tokenizeur/scripts/switch.2.test.php
  codephp <?php

  code : 
      _switch 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              _default 
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $x
                       "=" 
                      right : 
                          literals 2
