tests/tokenizeur/scripts/switch.1.test.php
  codephp <?php

  code : 
      _switch 
          parenthesis 
          ( "literals 1" )
          block 
          0 : 
              _case 
                  literals 2
                  block 
                  0 : 
                      _break 
                      Number : " "1""
          1 : 
              _case 
                  literals 3
                  block 
                  0 : 
                      _break 
                      Number : " "1""
          2 : 
              _default 
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $a
                       "=" 
                      right : 
                          literals 4
