tests/tokenizeur/scripts/switch.16.test.php
  codephp <?php

  code : 
      _switch 
          parenthesis 
          ( "variable $x" )
          block 
          0 : 
              _case 
                  literals 1
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $y
                       "=" 
                      right : 
                          literals 1
                  1 : 
                      _break 
                      Number : " "1""
          1 : 
              _default 
                  block 
                  0 : 
                      affectation 
                      left : 
                          variable $y
                       "=" 
                      right : 
                          literals 2
