tests/tokenizeur/scripts/ternaryop.22.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          ternaryop ?
          comparison variable $b  "<" functioncall variable $c ( arglist(variable $d) )  ? variable $e : literals f
              comparison 
              left : 
                  variable $b
              operateur :  "<"
              right : 
                  functioncall $c
                  function call : variable $c: 
                      arglist 
                      0 : 
                          variable $d
              variable $e
              literals f
